OrdererOrgs:
  - Name: Orderer
    Domain: alphachain.com
    EnableNodeOUs: true
    Specs:
      - Hostname: orderer
        SANS:
          - localhost

PeerOrgs:
  - Name: AlphaOrg
    Domain: alpha.alphachain.com
    EnableNodeOUs: true
    Template:
      Count: 1
      SANS:
        - localhost
    Users:
      Count: 1

  - Name: CustomsOrg
    Domain: customs.alphachain.com
    EnableNodeOUs: true
    Template:
      Count: 1
      SANS:
        - localhost
    Users:
      Count: 1
